### ISSUE TITLE
Temperature in Celsius 

### ISSUE THREAD

**Issue by familyofharris** [YinHangCode/homebridge-raspberrypi-temperature#1]
Hi is it possible to get the temperature in Celsius ? If so how ? Thanks in advance

**Comment by czdeee** [comment]
change you temperature unit in the Setting -- general -- langauge & region

**Comment by toshibochan** [comment]
I have my setting nest and iOS devices set to Celsius but only homebridge-nest give metemperature in Fahrenheit.  Other device I have Siri give me correct temperature in Celsius.

**Comment by toshibochan** [comment]
In the home app  everything show correct in Celsius but Siri only give me nest temperature in F. Hope someone fix that. And this problem is in homebridge-nest because my sensor connect to the raspberry pi Siri give me in Celsius.

**Comment by ratsoid** [comment]
Need this as well

**Comment by simplenotezy** [comment]
Only took 2 years, but here you go ;) https://github.com/YinHangCode/homebridge-raspberrypi-temperature/pull/12

Just waiting for @YinHangCode to merge
